/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class playn_android_AndroidNativeGL20 */

#ifndef _Included_playn_android_AndroidNativeGL20
#define _Included_playn_android_AndroidNativeGL20
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     playn_android_AndroidNativeGL20
 * Method:    glDrawElements
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_playn_android_AndroidGL20Native_glDrawElements
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     playn_android_AndroidNativeGL20
 * Method:    glVertexAttribPointer
 * Signature: (IIIZII)V
 */
JNIEXPORT void JNICALL Java_playn_android_AndroidGL20Native_glVertexAttribPointer
  (JNIEnv *, jobject, jint, jint, jint, jboolean, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
