name: Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Java 11
        run: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Check out PlayN
        uses: actions/checkout@v4

      - name: Build and run tests
        run: mvn -B install
